import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const ART_SIZE = Math.min(220, width - 140);

export const createStyles = (theme) => StyleSheet.create({
  backgroundImage: {
    flex: 1,
  },
  blurOverlay: {
    flex: 1,
    backgroundColor: 'rgba(8, 8, 8, 0.77)',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    fontFamily: 'Lexend_500Medium',
    color: theme.colors.onBackground,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  errorText: {
    marginTop: 16,
    fontSize: 18,
    fontFamily: 'Lexend_600SemiBold',
    color: theme.colors.error,
  },
  errorSubtext: {
    marginTop: 8,
    fontSize: 14,
    fontFamily: 'Lexend_400Regular',
    color: theme.colors.onBackground,
    opacity: 0.6,
    textAlign: 'center',
  },
  // Sticky header (back + more icons)
  stickyHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  stickyNavIcon: {
    color: theme.colors.onBackground,
    padding: 4,
    textShadowColor: theme.colors.primary,
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 0,
  },
  // Art glow container (rounded media art with primary-colored glow)
  artContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 100,
    paddingBottom: 14,
  },
  artShadow: {
    borderRadius: 18,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.5,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 18,
  },
  artImage: {
    width: ART_SIZE,
    height: ART_SIZE,
    borderRadius: 18,
  },
  titleBlock: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 0,
  },
  albumName: {
    fontSize: 23,
    fontFamily: 'Lexend_700Bold',
    color: theme.colors.onSurface,
    textShadowColor: theme.colors.primary,
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 0,
  },
  albumArtist: {
    fontSize: 14,
    fontFamily: 'Lexend_500Medium',
    color: theme.colors.primary,
    marginTop: 4,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  badge: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 99,
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  badgeText: {
    fontSize: 11,
    fontFamily: 'Lexend_500Medium',
    color: theme.colors.onSurface,
    opacity: 0.6,
  },
  playAreaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
    marginBottom: 14,
  },
  playPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 26,
    paddingVertical: 9,
    borderRadius: 99,
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.45,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  playPillText: {
    fontSize: 14,
    fontFamily: 'Lexend_700Bold',
    color: '#000',
    letterSpacing: 0.2,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.13)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.borderLowOpacity,
  },
  discHeader: {
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: 'transparent',
  },
  discHeaderText: {
    fontSize: 11,
    fontFamily: 'Lexend_700Bold',
    color: theme.colors.onSurface,
    opacity: 0.5,
    letterSpacing: 1.2,
  },
  listContainer: {
    paddingBottom: 120,
  },
  // Album track rows — no art
  songItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderLowOpacity,
    backgroundColor: 'transparent',
  },
  songItemPlaying: {
    backgroundColor: theme.colors.playingBackground,
  },
  heartWrapper: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginLeft: 4,
  },
  heartIcon: {
    color: theme.colors.primary,
  },
  trackNumberWrapper: {
    width: 22,
    alignItems: 'center',
    marginRight: 10,
    flexShrink: 0,
  },
  trackNumber: {
    fontSize: 12,
    fontFamily: 'Lexend_500Medium',
    color: theme.colors.onSurface,
    opacity: 0.4,
  },
  nowPlayingIcon: {
    color: theme.colors.primary,
  },
  songInfo: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  songTitle: {
    fontSize: 13.5,
    fontFamily: 'Lexend_600SemiBold',
    color: theme.colors.onSurface,
  },
  songTitlePlaying: {
    color: theme.colors.primary,
  },
  songArtistText: {
    fontSize: 11.5,
    fontFamily: 'Lexend_400Regular',
    color: theme.colors.onSurface,
    opacity: 0.55,
    marginTop: 1,
  },
  songArtistPlaying: {
    color: theme.colors.primary,
    opacity: 0.7,
  },
  songDuration: {
    fontSize: 12,
    fontFamily: 'Lexend_400Regular',
    color: theme.colors.onSurface,
    opacity: 0.4,
    marginRight: 2,
    flexShrink: 0,
  },
  menuButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  emptyState: {
    paddingTop: 80,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 18,
    fontFamily: 'Lexend_600SemiBold',
    color: theme.colors.onBackground,
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    fontFamily: 'Lexend_400Regular',
    color: theme.colors.onBackground,
    opacity: 0.6,
    textAlign: 'center',
    marginTop: 8,
    paddingHorizontal: 32,
  },
});
